// <auto-generated />
using System;
using ClavierOr;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClavierOr.Migrations
{
    [DbContext(typeof(ClavierOrContext))]
    [Migration("20260212095141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ClavierOr.Models.Historique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JoueurId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.HasIndex("PartieId");

                    b.ToTable("Historiques");
                });

            modelBuilder.Entity("ClavierOr.Models.Joker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstUtilise")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JoueurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.ToTable("Jokers");
                });

            modelBuilder.Entity("ClavierOr.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BossVaincus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateDernierBoss")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstClavierOr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExperienceActuelle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NiveauActuel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartieId");

                    b.HasIndex("RoleId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("ClavierOr.Models.Partie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeilleurStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionActuelleIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreakActuelle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("ClavierOr.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categorie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enonce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsAttribues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempsLimite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartieId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ClavierOr.Models.Reponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explication")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("ClavierOr.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvantageSpecial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MultiplicateurScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ClavierOr.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonnesReponses")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePartie")
                        .HasColumnType("TEXT");

                    b.Property<int>("JokersUtilises")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JoueurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MauvaisesReponses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PourcentageReussite")
                        .HasColumnType("REAL");

                    b.Property<int>("StreakMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TempsTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.HasIndex("PartieId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ClavierOr.Models.Historique", b =>
                {
                    b.HasOne("ClavierOr.Models.Joueur", "Joueur")
                        .WithMany()
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClavierOr.Models.Partie", "Partie")
                        .WithMany()
                        .HasForeignKey("PartieId");

                    b.Navigation("Joueur");

                    b.Navigation("Partie");
                });

            modelBuilder.Entity("ClavierOr.Models.Joker", b =>
                {
                    b.HasOne("ClavierOr.Models.Joueur", null)
                        .WithMany("Jokers")
                        .HasForeignKey("JoueurId");
                });

            modelBuilder.Entity("ClavierOr.Models.Joueur", b =>
                {
                    b.HasOne("ClavierOr.Models.Partie", null)
                        .WithMany("Joueurs")
                        .HasForeignKey("PartieId");

                    b.HasOne("ClavierOr.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClavierOr.Models.Question", b =>
                {
                    b.HasOne("ClavierOr.Models.Partie", null)
                        .WithMany("Questions")
                        .HasForeignKey("PartieId");
                });

            modelBuilder.Entity("ClavierOr.Models.Reponse", b =>
                {
                    b.HasOne("ClavierOr.Models.Question", "Question")
                        .WithMany("Reponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ClavierOr.Models.Score", b =>
                {
                    b.HasOne("ClavierOr.Models.Joueur", "Joueur")
                        .WithMany("Scores")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClavierOr.Models.Partie", "Partie")
                        .WithMany("Scores")
                        .HasForeignKey("PartieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Partie");
                });

            modelBuilder.Entity("ClavierOr.Models.Joueur", b =>
                {
                    b.Navigation("Jokers");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ClavierOr.Models.Partie", b =>
                {
                    b.Navigation("Joueurs");

                    b.Navigation("Questions");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ClavierOr.Models.Question", b =>
                {
                    b.Navigation("Reponses");
                });
#pragma warning restore 612, 618
        }
    }
}
